### ISSUE TITLE
Initial Implementation of Formkit-Ninja as forms backend

### ISSUE THREAD

**Issue by joshbrooks** [catalpainternational/formkit-ninja#1]
I'm throwing @AneeshNi47 in the deep end asking him to review an entire new repository :scream: :tada: 

https://github.com/catalpainternational/partisipa-import/pull/137 implements this project for the first time, probably a little buggy, definitely an `alpha` release

## Conditions of Satisfaction:

 - [x] A developer can pull the repo (python 3.10 or greater) and `poetry install`
 - [x] As a developer I can run `poetry run pytest`
 - [x] I can visit the admin site for formkit-ninja and nothing bad happens
 - [x] I can visit the api docs site for formkit-ninja and nothing bad happens
 - [x] As a developer I don't see anything in the code which makes me very upset or confused

**Comment by joshbrooks** [comment]
Please close this issue if you think the above points are met, otherwise drop some comments and I'll address them

**Comment by RobertoMaurizzi** [comment]
Hmmm...
from a Python 3.11 installed in Ubuntu 20.04 WSL I cloned the repo then run poetry install.
Poetry run pytest is successful.
Trying to run the application, I first get that there are unapplied changes to the models and that I need to run makemigrations and migrate.
After that, I create a superuser that can log in and see the admin. The `FORMKIT NINJA` models are populated with quite a bit of data.
The /api endpoint however is strange: if anything tries to access `/api/openapi.json`, the test server runner quits without any error 😅 
`/api/docs` says it can't load the openapi.json (because at that point there's no server running anymore).

Do I need to create some more configuration documents from the admin?
